language: node_js
services:
- docker
cache:
  directories:
  - ~/.nvm
  - node_modules
env:
  global:
  - RELEASE_BRANCH="master"
  - DOCKER_HUB_ACCOUNT="edenlabllc"
  - MAIN_BRANCHES="master develop"
  - secure: "jRBh330W/sl1EBmyXdd+zXSp1YIEShclxNI3KmLLu4W4nV4tXDDmKOO4O0adnVYRvV52xJYHTvEaR9Y8rse1xfhBr3rBkmcgCqsUav2pOnlH3E5hyn7yx++3jdMXyS9wle1+1U/4Ii5IAxvbVcSJiRwqMt9vD8CI13PDANU1dGTQTtc3ZyFrlJfB7rlu5Z6CR+acZtp84hwWzT77iEEoWo1h+jOlS3jc4EPqTySdIZighCzN7YUUx1+ItBX0wwnfXC5MeVTj/Kp5yaYYIGPa9JWWAmzNReqYEs5NvdFWPzazl2Bcj2OHTWyDpxuP5KJjjzYpTP7jHGDg1Hb/D0cRDSQn2LIOwfAuU9TYN5WRgoTrrilKSJqxhJ3cVxgmraGJtxNt57BHr3+43iv+1HRgnj+LsmFw+NT/iTuD/gtwM6rXOcubtui7t9eI4exJoXmyKnNM1ZoZi96znSJpemHp9+EfnPa6inPtxnNvdr1MApN6tVbu7Z71LVSAE3dAyxeJHyHRV/+uLZAL/wgICS3dxLCWp10QO5JPSsWeOnitaswqBBEe54pXXYdcIzHXaIkIltCXonw466ewue/LP0e8CXrb64EYNA0E+D1MLotH86sUfZnzEEW/GgiPiSCDBAmlEdhbyZ0i+xK5SOJrmsruBhCfklNnVZfi5SGbF72jPE4="
node_js:
- 7.5.0
before_install:
- npm run docker:up
- chmod -R +x bin
script:
- npm run test
- npm run lint
- ./bin/version-increment.sh
- ./bin/build.sh
- ./bin/start.sh
- sleep 5
- docker ps
- RUNNING_CONTAINERS=`docker ps | wc -l`; if [ "${RUNNING_CONTAINERS//[[:space:]]/}"
  == "1" ]; then echo "[E] Container is not started\!"; docker logs nhs.admin.web
  --details --since 5h; exit 1; fi;
- npm run nightwatch -- -e travis
- sleep 5
after_success:
- ./bin/ci/push.sh
